//INCREMENT
export const INCREMENT_COUNTER="INCREMENT_COUNTER"
export const DECREMENT_COUNRER="DECREMENT_COUNTER"

//REDUX-SAGAS
export const SIGNUP_USER="SIGNUP_USER"
export const EMAIL_VERYFICATON="EMAIL_VERYFICATON"

//SIGNUP ALERT
export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

//LOGIN
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_LOGD = "LOGIN_LOGD"

//LOGOUT
export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_LOGED = "LOGOUT_LOGED"

//GOOGLE SIGNUP
export const GOOGLE_SIGNUP = "GOOGLE_SIGNUP"

//FORGET PASSWORD
export const FORGET_PASSWORD = "FORGET_PASSWORD"