export const INCREMENT_COUNTER="INCREMENT_COUNTER"
export const DECREMENT_COUNRER="DECREMENT_COUNTER"

//REDUX-SAGAS
export const SIGNUP_USER="SIGNUP_USER"
export const EMAIL_VERYFICATON="EMAIL_VERYFICATON"

//ALERT
export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"